[en]
  title = "Ayman Barghout's Blog"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ar]
  title = "مدونة أيمن برغوت"
  languageName = "العربية"
  weight = 2
  languagedir = "rtl"
  contentdir = "content/ar"
