[[main]]
  identifier = "about"
  name = "نبذة عني"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "الأرشيف"
  url = "archive"
  weight = 2

[[main]]
  identifier = "posts"
  name = "المدونة"
  url = "posts"
  weight = 3

[[main]]
  identifier = "showcase"
  name = "المشاريع"
  url = "showcase"
  weight = 4
